### ISSUE TITLE
Audio Settings - Source change to BT

### ISSUE THREAD

**Issue by mikegapinski** [rhysmorgan134/node-CarPlay#19] opened 2023-09-07 22:31 UTC
Hey!

I am wondering if you know how to configure the audio source in the config. The AutoKit app gives an option to switch from Box to Bluetooth (in this option the phone sends the bt audio straight to the car/headunit via bt and only video is used in CarPlay).

Best regards

**Comment by mikegapinski** [comment] 2023-09-07 22:36
cc @steelbrain; maybe you have stumbled upon this

**Comment by mikegapinski** [comment] 2023-09-08 00:49
I took a glimpse on the apk with Jadx. This setting is stored in SharedPreferences under a key "AudioTransferMode". This is a simple flag that is being sent to the box at some point:

`    /* renamed from: P */
    public void m1662P(boolean z) {
        this.f5560l.mo3765i(Boolean.valueOf(z));
        C1325c0.m2653l().m2665E("AudioTransferMode", Boolean.valueOf(z));
        if (C1483d.m2058i()) {
            C1483d.f5327o.m1969f0(z);
        }
    }`
    
    There is a bit of logic to convert that into a command that is sent to the box:
    
        /* renamed from: q0 */
    private boolean m1947q0(int i, int i2) {
        boolean booleanValue = this.f5384o.m1395a().booleanValue();
        if (booleanValue) {
            C1504l c1504l = new C1504l(this, 4);
            c1504l.f5429a.f5410c = i;
            c1504l.f5429a.f5409b = 4;
            c1504l.m1902c();
            c1504l.m1901d().putInt(0, i2);
            c1504l.m1896i();
            synchronized (this) {
                booleanValue = C1483d.m2062e0(c1504l.m1898g(), c1504l.m1897h()) ? C1483d.m2062e0(c1504l.m1900e(), c1504l.m1899f()) : false;
                C1611m.m1423c("BoxProtocol,sendCmd: " + i + " " + i2 + " " + booleanValue);
            }
        } else {
            C1611m.m1421e("BoxProtocol,sendCmd: bOpened_ = false, cmd = " + i + "," + i2);
        }
        return booleanValue;
    }
    
    The values for int i and int i2 are 8, 22 or 8,23 depending on the boolean
    
    I guess that this message can be added to: https://github.com/rhysmorgan134/node-CarPlay/blob/next/src/modules/messages.ts and dispatched right after the device is connected. Pardon my lack of understanding how your implementation works, this is completely not my stack and I want to use your project as a playground. I am looking into implementing the protocol in C and using making a Android NDK library that would be used in a open source alternative for the AutoKit app that is hot garbage...

**Comment by gozmanyoni** [comment] 2023-09-08 07:33
@mikegapinski - Added this in this PR - https://github.com/rhysmorgan134/node-CarPlay/pull/21

**Comment by mikegapinski** [comment] 2023-09-08 07:35
Thank you! My apk research made it easy for you. I will check it and confirm that it works

**Comment by gozmanyoni** [comment] 2023-09-08 08:12
@mikegapinski Thank you for the research - made it easy indeed :) I tested it locally and when its on the phone keeps playing and never switches the audio to the dongle

**Comment by mikegapinski** [comment] 2023-09-08 08:16
Nice!

I need to take a glimpse at how they are handling multiple iPhones for wireless CarPlay - there is a GUI for managing those in the app and I’ve seen some props used to get a list of MAC addresses.

Android auto also has some separate config for resolution, but the audio channel settings doesn’t work for AA sadly - they did not implement it I guess

Wysyłane z aplikacji Outlook dla systemu iOS<https://aka.ms/o0ukef>
________________________________
Od: gozmanyoni ***@***.***>
Wysłane: Friday, September 8, 2023 10:12:47 AM
Do: rhysmorgan134/node-CarPlay ***@***.***>
DW: Michał Gapiński ***@***.***>; Mention ***@***.***>
Temat: Re: [rhysmorgan134/node-CarPlay] Audio Settings - Source change to BT (Issue #19)


@mikegapinski<https://github.com/mikegapinski> Thank you for the research - made it easy indeed :) I tested it locally and when its on the phone keeps playing and never switches the audio to the dongle

**Comment by gozmanyoni** [comment] 2023-09-11 12:23
@mikegapinski were you able to confirm this on your side?

**Comment by gozmanyoni** [comment] 2023-09-19 09:48
Closing this as it seems to work as intended with my tests.

**Closed by gozmanyoni** 2023-09-19 09:48 UTC
